name: "BuhTuh tests: pytest mypy"

on:
  push:
    paths:
      - 'buhtuh/**'
      # Also run if we update this file, or any other workflow
      - '.github/**'

jobs:
  typecheck-and-run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        # Configure cache for the files that pip downloads. At the end of the steps the path gets cached
        # (if the cache keys doesn't exist yet). If the cache key exists it gets restored in this step.
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          key: pip-${{ matrix.python-version }}-${{ hashFiles('buhtuh/requirements.txt', 'buhtuh/requirements-dev.txt') }}
      - name: Install dependencies
        run: |
          cd buhtuh
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt -r requirements.txt
      - name: Typecheck with mypy
        continue-on-error: True  # TODO: set this to false after fixing all mypy problems
        run: |
          cd buhtuh
          mypy buhtuh
      - name: Test with pytest
        run: |
          cd buhtuh
          pytest tests/unit/
# TODO: also add the functional tests that rely on Postgres being available
